---
default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        exclude: ^changelogs/changelog\.yaml$
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint.yml"]

  - repo: https://github.com/psf/black
    rev: "26.5.1"
    hooks:
      - id: black
        files: ^(plugins|tests)/.*\.py$

  - repo: https://github.com/ansible/ansible-lint
    rev: v26.6.0
    hooks:
      - id: ansible-lint
        files: \.(yml|yaml)$
        exclude: ^(\.github/|\.devcontainer/|changelogs/)
